### PR TITLE
Added ability to toggle sentry mode

### PR DESCRIPTION
**Pull request by DoctorMcKay**
This is how it appears to be done in the latest version of the Android app. Unfortunately, I don't have an AP 2.5 car so I couldn't test this change.

### CODE REVIEW

**Comment by mseminatore** [comment]
Thank you.  I also don't have an AP2.5 vehicle for testing!  But I will review the PR and see how this looks.

**Comment by DoctorMcKay** [comment]
The built is failing because I'm inept :wink:.

No, I didn't add any tests or update apiary. Just ran docgen.

**Comment by mseminatore** [comment]
It looks like the build failed again, I haven't had a chance to look at the log yet.  Did you by chance add the endpoint to the apiary file and add a test case for this to test.js?

**Comment by mseminatore** [comment]
@DoctorMcKay OK, the build succeeded. I'll take a look at the PR over the weekend and if it looks good I'll update the apiary file, add test cases, and merge.  Thanks!

**Comment by keithamus** [comment]
Can confirm this API works.

**Comment by mseminatore** [comment]
@keithamus Excellent, thanks for confirming!

**Pull request merged**
