### PR TITLE
Fix login/logout samples

### PR DESCRIPTION
**Pull request by Niek**
Fixes missing TeslaJS import due to capitalization

### CODE REVIEW

**Comment by mseminatore** [comment]
@Niek What OS are you testing against? The lib works on Windows and MacOS as is.

**Comment by Niek** [comment]
@mseminatore both macOS (HFS+ by default) and Windows have case-insensitive filesystems. On Linux you need to specify the correctly capitalized files.

**Comment by mseminatore** [comment]
@Niek I am a little confused as our automated build process builds and tests on Linux. Here are the details:

Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by Niek** [comment]
@mseminatore I don't think that specifically tests the login and logout samples? It's only those 2 that have the issue. FYI this is what I see on a case-sensitive FS:
```console
$ node node_modules/teslajs/samples/login.js
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '../TeslaJS'
Require stack:
- /path/node_modules/teslajs/samples/login.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path/node_modules/teslajs/samples/login.js:12:11)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/path/node_modules/teslajs/samples/login.js' ]
}
```

**Comment by mseminatore** [comment]
@Niek You are 100% correct, not sure how I forgot that the tests don't run the samples. :)

**Pull request merged**
