### PR TITLE
Add ChargingAmps, ScheduledCharging and ScheduledDeparture API calls

### PR DESCRIPTION
**Pull request by GaPhi**
Consider username/password as access/refresh tokens when username does not include '@' (email address)

This is only a way to be able to use the library even when Tesla changes the authentication sequence... But it could also be a more permanent feature...

### CODE REVIEW

**Comment by GaPhi** [comment]
I removed auth.js patch and added calls to those new APIs.

**Comment by GaPhi** [comment]
Fully tested with GaPhi/node-red-contrib-tesla

**Comment by GaPhi** [comment]
- WindowControl lat/lon parameters added
- RemoteStart password removed
- Doc & tests updated

Tested with @gaphi/teslajs 4.9.12-4

**Comment by mseminatore** [comment]
@GaPhi Thank you for the PR! Sorry for the long delay on merge.

**Comment by GaPhi** [comment]
Thanks! I will be able to go back to the main branch as soon as you release it!
Happy Xmas and new year!

**Pull request merged**
