### PR TITLE
Implemented new authentication flow

### PR DESCRIPTION
**Pull request by DoctorMcKay**
Some time ago, Tesla updated the mobile app to use a web-based authentication flow. Suspicion is that this is in preparation for 2FA. In either case, it seems prudent to update the library to use the new authentication flow in the event that the old flow quits working.

Since it's a fairly involved process, requiring 4 HTTP requests, I decided to create a separate file to handle auth. Hope you don't mind.

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
I've added support for MFA auth, which necessitated changing the API for the login function. I've made it backwards-compatible with the old API so it's not a breaking change, but if you'd rather do this some other way that's fine too.

**Comment by mseminatore** [comment]
@DoctorMcKay Hi, sorry for the long delay. Covid has re-allocated my time. I just started looking into this PR. I merged this into my own branch for testing and I am getting the following failure on login. Any thoughts?

TeslaJS.login()

Response: undefined

Body: undefined
TeslaJS.login() completed.
TypeError: Cannot read property 'forEach' of null
    at D:\dev\TeslaJS\src\auth.js:51:26
    at tryCallOne (D:\dev\TeslaJS\node_modules\promise\lib\core.js:37:12)
    at D:\dev\TeslaJS\node_modules\promise\lib\core.js:123:15
    at flush (D:\dev\TeslaJS\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mseminatore** [comment]
@DoctorMcKay Ah, it looks like the endpoint name changed since your initial PR. Can you please confirm that the correct endpoint on line 36 of auth.js should be `https://auth.tesla.com/oauth2/v3/authorize` instead of `https://auth-global.tesla.com/oauth2/v3/authorize`?

**Comment by DoctorMcKay** [comment]
auth-global.tesla.com redirects to auth.tesla.com for me.

**Comment by mseminatore** [comment]
@DoctorMcKay did you test this PR in the last day or so? The redirect does not appear to be working for me. If I use auth-global it fails.

**Comment by DoctorMcKay** [comment]
I haven't tested this recently, no. Maybe the server was having issues when you tried it?

**Pull request merged**
